%% drgCaImAn_dropc_ca_only.m
%
% Needs as an input the ouput file from drgCaImAn_dropc
%
close all
clear all

dt=0.00815;


%% Get the raw and inferred traces generated by drgCaimAn_script
[fnameca,pnameca,nCancel] = uigetfile({'*.mat;*.hdf5;*.csv'},'Select the output file from CaimAn, EXTRACT or ImageJ...');
if nCancel
    inputPath = [pnameca,fnameca];
    pnameStart = pnameca;
    %save('timeCorr_cfg.mat','pnameStart','-append');
else
    error('Cancelled')
end


this_filename=[pnameca fnameca];

if strcmp(this_filename(end-3:end),'.mat')
    %This reads the extract file
    load(this_filename)
    traces=zeros(size(output.temporal_weights,1),size(output.temporal_weights,2));
    for traceNo=1:size(output.temporal_weights,2)
        traces(:,traceNo)=output.temporal_weights(:,traceNo);
    end
    traces=traces';
else
    if strcmp(this_filename(end-4:end),'.hdf5')
        %This is an hdf5 generated by CaImAn
        traces=h5read(this_filename,'/traces' )';   
    else
        %This is a csv file created from ImageJ
        traces=readmatrix([handles_choice.PathNamecsv{fileNo} handles_choice.csvFileName{fileNo}]);
    end
end
 
sz_traces=size(traces);
no_traces=sz_traces(1);
no_images=sz_traces(2);

fprintf(1, ['\ndrgCaImAn_dropc run for ' this_filename '\n\n']);

try
    close 1
catch
end

hFig1 = figure(1);
set(hFig1, 'units','normalized','position',[.05 .1 .85 .8])

hold on
 
% Determine the y spacing of the traces
y_shift=2*(prctile(traces(:),95)-prctile(traces(:),5));

%Plot the traces
time=[1:no_images]*dt;
for trNo=1:no_traces
% for trNo=1:20
    plot(time,traces(trNo,:)+y_shift*trNo,'-k','LineWidth',1)
end

ylim([-y_shift*0.2 (no_traces+2)*y_shift])
xlabel('time (s)')
ylabel('deltaF/F')
title(fnameca(1:end-4))

xlim([30  40])
ylim([18000 24000])
tic
ymin=0;
ymax=ymin+7000;
while ymax<120000
    ylim([ymin ymax])
    ymin=ymin+5000;
    ymax=ymin+7000;
    this_toc=toc;
    figure(1)
    while toc-this_toc<5
    end
end
ylim([19100 27500])

pffft=1;
