%% drgCaImAn_plot_traces.m
%
% Needs as an input the ouput file from drgCaImAn_dropc
%
close all
clear all

%% choices
plot_raw=1;
ref_win=[-5 -1.5];
dt=1/4;


%% Get the raw and inferred traces generated by drgCaimAn_script
[fnameca,pnameca,nCancel] = uigetfile({'*.mat'},'Select the output file ...');
if nCancel
    inputPath = [pnameca,fnameca];
    pnameStart = pnameca;
    %save('timeCorr_cfg.mat','pnameStart','-append');
else
    error('Cancelled')
end


this_filename=[pnameca fnameca];

if strcmp(this_filename(end-3:end),'.mat')
    %This reads the extract file
    load(this_filename)
    traces=zeros(size(output.temporal_weights,1),size(output.temporal_weights,2));
    for traceNo=1:size(output.temporal_weights,2)
        traces(:,traceNo)=output.temporal_weights(:,traceNo);
    end
    traces=traces';
else
    if strcmp(this_filename(end-4:end),'.hdf5')
        %This is an hdf5 generated by CaImAn
        traces=h5read(this_filename,'/estimates/F_dff' );
    else
        %This is a csv file created from ImageJ
        traces=readmatrix(this_filename);
    end
end

 
sz_traces=size(traces);

no_traces=sz_traces(1);
no_images=sz_traces(2);

fprintf(1, ['\ndrgCaImAn_plot_EXTRACT_traces run for ' fnameca '\n\n']);

% Determine the y spacing of the traces
y_shift=1.2*(prctile(traces(:),95)-prctile(traces(:),5));

try
    close 1
catch
end

hFig1 = figure(1);
set(hFig1, 'units','normalized','position',[.05 .1 .85 .8])

hold on

%Plot the traces
time=[1:no_images]*dt;
for trNo=1:no_traces
% for trNo=1:20
    plot(time,traces(trNo,:)+y_shift*trNo,'-k','LineWidth',1)
end

ylim([-y_shift*0.2 (no_traces+2)*y_shift])
xlabel('time (s)')
ylabel('deltaF/F')
title(fnameca(1:end-4))

pffft=1;